package com.airpg.services;

import com.airpg.agents.AgentService;
import com.airpg.agents.NPCAgent;
import com.airpg.domain.GameState;
import com.airpg.domain.NPC;
import com.airpg.domain.Quest;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.jboss.logging.Logger;

import java.util.UUID;

/**
 * Service for managing NPC interactions and behaviors.
 * Handles NPC dialogue, quest generation, and NPC-driven events.
 */
@ApplicationScoped
public class NPCService {
    
    private static final Logger LOG = Logger.getLogger(NPCService.class);
    
    @Inject
    AgentService agentService;
    
    /**
     * Have an NPC speak/respond to the player
     */
    public String getNPCDialogue(NPC npc, String playerMessage, GameState gameState) {
        NPCAgent agent = agentService.getNPCAgent(npc);
        
        String context = String.format("""
                You are %s, a %s.
                Your role: %s
                Your personality: %s
                Your agenda: %s
                Current location: %s
                You are %s.
                
                The player says: "%s"
                
                Respond as this character.
                """,
                npc.getName(),
                npc.getRole(),
                npc.getRole(),
                npc.getPersonality(),
                npc.getAgenda(),
                npc.getLocation(),
                npc.isHostile() ? "hostile to the player" : "neutral or friendly",
                playerMessage
        );
        
        String dialogue = agent.speak(context);
        LOG.debugf("NPC %s responded to player", npc.getName());
        return dialogue;
    }
    
    /**
     * Have NPC react to a player action
     */
    public String getNPCReaction(NPC npc, String playerAction, GameState gameState) {
        NPCAgent agent = agentService.getNPCAgent(npc);
        
        String context = String.format("""
                You are %s (%s).
                Personality: %s
                Agenda: %s
                
                The player just did: %s
                
                How do you react? (Stay in character)
                """,
                npc.getName(),
                npc.getRole(),
                npc.getPersonality(),
                npc.getAgenda(),
                playerAction
        );
        
        return agent.reactToPlayerAction(context);
    }
    
    /**
     * Have NPC generate a quest for the player
     */
    public Quest generateQuestFromNPC(NPC npc, GameState gameState) {
        if (!npc.isQuestGiver()) {
            LOG.warnf("NPC %s is not a quest giver", npc.getName());
            return null;
        }
        
        NPCAgent agent = agentService.getNPCAgent(npc);
        
        String context = String.format("""
                You are %s, a %s.
                Your agenda: %s
                Your location: %s
                Hero level: %d
                
                Generate a quest that fits your character and agenda.
                The quest should be something the player can help you with.
                """,
                npc.getName(),
                npc.getRole(),
                npc.getAgenda(),
                npc.getLocation(),
                gameState.getHero().getLevel()
        );
        
        String questData = agent.generateQuest(context);
        
        // Parse the quest data (format: "TITLE: [title] | DESCRIPTION: [description]")
        Quest quest = parseQuestFromAgentResponse(questData, npc);
        
        if (quest != null) {
            gameState.addQuest(quest);
            LOG.infof("Quest '%s' generated by NPC %s", quest.getTitle(), npc.getName());
        }
        
        return quest;
    }
    
    /**
     * Parse quest from agent response
     */
    private Quest parseQuestFromAgentResponse(String response, NPC npc) {
        try {
            String[] parts = response.split("\\|");
            String title = parts[0].replace("TITLE:", "").trim();
            String description = parts[1].replace("DESCRIPTION:", "").trim();
            
            return Quest.builder()
                    .id(UUID.randomUUID().toString())
                    .title(title)
                    .description(description)
                    .givenBy(npc.getId())
                    .status(Quest.QuestStatus.ACTIVE)
                    .isMainQuest(false)
                    .experienceReward(50)
                    .build();
        } catch (Exception e) {
            LOG.errorf("Failed to parse quest from response: %s", response);
            return null;
        }
    }
    
    /**
     * Create a sample NPC for the game
     */
    public NPC createSampleNPC(String location) {
        return NPC.create(
                UUID.randomUUID().toString(),
                "Old Sage Marcus",
                "Wizard",
                location,
                "Seeks ancient knowledge and wants to prevent dark magic from spreading",
                "Wise, cautious, speaks in riddles, values knowledge over gold",
                false
        );
    }
}
