-- V1: Create game_saves table (main save metadata)
CREATE TABLE game_saves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id VARCHAR(36) NOT NULL UNIQUE,
    save_name VARCHAR(100) NOT NULL,
    hero_name VARCHAR(100) NOT NULL,
    hero_class VARCHAR(50) NOT NULL,
    hero_level INT NOT NULL,
    current_location VARCHAR(200) NOT NULL,
    main_goal VARCHAR(500) NOT NULL,
    game_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
