-- V2: Create heroes table (1:1 with game_saves)
CREATE TABLE heroes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    character_class VARCHAR(50) NOT NULL,
    level INT NOT NULL DEFAULT 1,
    experience INT NOT NULL DEFAULT 0,
    strength INT NOT NULL,
    intelligence INT NOT NULL,
    agility INT NOT NULL,
    constitution INT NOT NULL,
    charisma INT NOT NULL,
    current_health INT NOT NULL,
    max_health INT NOT NULL,
    current_mana INT NOT NULL,
    max_mana INT NOT NULL,
    armor_bonus INT NOT NULL DEFAULT 0,
    weapon_bonus INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_hero_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
