-- V3: Create team_members table (1:N with game_saves)
CREATE TABLE team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL,
    member_id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    character_class VARCHAR(50) NOT NULL,
    personality VARCHAR(500),
    backstory VARCHAR(1000),
    loyalty INT NOT NULL DEFAULT 50,
    strength INT NOT NULL,
    intelligence INT NOT NULL,
    agility INT NOT NULL,
    constitution INT NOT NULL,
    charisma INT NOT NULL,
    current_health INT NOT NULL,
    max_health INT NOT NULL,
    current_mana INT NOT NULL,
    max_mana INT NOT NULL,
    armor_bonus INT NOT NULL DEFAULT 0,
    weapon_bonus INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_team_member_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
