-- V4: Create npcs table (1:N with game_saves)
CREATE TABLE npcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL,
    npc_id VARCHAR(36) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    location VARCHAR(200),
    agenda VARCHAR(500),
    personality VARCHAR(500),
    is_hostile BOOLEAN NOT NULL DEFAULT FALSE,
    is_quest_giver BOOLEAN NOT NULL DEFAULT FALSE,
    strength INT NOT NULL,
    intelligence INT NOT NULL,
    agility INT NOT NULL,
    constitution INT NOT NULL,
    charisma INT NOT NULL,
    current_health INT NOT NULL,
    max_health INT NOT NULL,
    current_mana INT NOT NULL,
    max_mana INT NOT NULL,
    armor_bonus INT NOT NULL DEFAULT 0,
    weapon_bonus INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_npc_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
