-- V5: Create quests table (1:N with game_saves)
CREATE TABLE quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL,
    quest_id VARCHAR(36) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    given_by VARCHAR(36),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_main_quest BOOLEAN NOT NULL DEFAULT FALSE,
    experience_reward INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_quest_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
