-- V6: Create story_history table (1:N with game_saves)
CREATE TABLE story_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL,
    event_order INT NOT NULL,
    event_text VARCHAR(2000) NOT NULL,
    CONSTRAINT fk_story_history_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
