-- V7: Create agent_memories table (AI chat history for NPCs/companions)
CREATE TABLE agent_memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_save_id BIGINT NOT NULL,
    memory_id VARCHAR(100) NOT NULL,
    message_index INT NOT NULL,
    message_type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT fk_memory_game_save FOREIGN KEY (game_save_id)
        REFERENCES game_saves(id) ON DELETE CASCADE
);
